services:
  auditwriter:
    image: auditwriter
    build: ./audit-writer  
    restart: always
    volumes:
      - ./keys/private_key.pem:/auditwriter/private_key.pem:ro
    ports:
      - "9010:9010"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/auditdb
      PRIVATE_KEY_PATH: /auditwriter/private_key.pem
      BOOTSTRAP_SERVERS: broker:9092

  auditverifier:
    image: auditverifier
    build: ./audit-verifier
    volumes:
      - ./keys/public_key.pub:/auditverifier/public_key.pub:ro
    restart: always
    ports:
      - "9011:9011"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/auditdb
      PUBLIC_KEY_PATH: /auditverifier/public_key.pub 

  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auditdb

  broker:
    image: apache/kafka:latest
    restart: always
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
