spring:
  application:
    name: audit-writer
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auditdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    log-audit: log_audit_topic
  consumer:
    auto-offset-reset: earliest
    group-id: audit
